= auditor.actor_usr_lifecycle (view)
:description: View reference for auditor.actor_usr_lifecycle

xref:schemas/auditor.adoc[↑ auditor schema]

[NOTE]
====
This is a *database view*, not a base table. It has no triggers, indexes, or FK constraints of its own. Querying this view may be more efficient than joining the underlying tables directly.
====

== Columns

[cols="2,2,1,4"]
|===
|Column |Type |Nullable |Notes

| audit_id
| `bigint`
| Yes
| 

| audit_time
| `timestamp with time zone`
| Yes
| 

| audit_action
| `text`
| Yes
| 

| audit_user
| `integer`
| Yes
| 

| audit_ws
| `integer`
| Yes
| 

| id
| `integer`
| Yes
| 

| card
| `integer`
| Yes
| 

| profile
| `integer`
| Yes
| 

| usrname
| `text`
| Yes
| 

| email
| `text`
| Yes
| 

| passwd
| `text`
| Yes
| 

| standing
| `integer`
| Yes
| 

| ident_type
| `integer`
| Yes
| 

| ident_value
| `text`
| Yes
| 

| ident_type2
| `integer`
| Yes
| 

| ident_value2
| `text`
| Yes
| 

| net_access_level
| `integer`
| Yes
| 

| photo_url
| `text`
| Yes
| 

| prefix
| `text`
| Yes
| 

| first_given_name
| `text`
| Yes
| 

| second_given_name
| `text`
| Yes
| 

| family_name
| `text`
| Yes
| 

| suffix
| `text`
| Yes
| 

| guardian
| `text`
| Yes
| 

| pref_prefix
| `text`
| Yes
| 

| pref_first_given_name
| `text`
| Yes
| 

| pref_second_given_name
| `text`
| Yes
| 

| pref_family_name
| `text`
| Yes
| 

| pref_suffix
| `text`
| Yes
| 

| name_keywords
| `text`
| Yes
| 

| name_kw_tsvector
| `tsvector`
| Yes
| 

| alias
| `text`
| Yes
| 

| day_phone
| `text`
| Yes
| 

| evening_phone
| `text`
| Yes
| 

| other_phone
| `text`
| Yes
| 

| mailing_address
| `integer`
| Yes
| 

| billing_address
| `integer`
| Yes
| 

| home_ou
| `integer`
| Yes
| 

| dob
| `date`
| Yes
| 

| active
| `boolean`
| Yes
| 

| master_account
| `boolean`
| Yes
| 

| super_user
| `boolean`
| Yes
| 

| barred
| `boolean`
| Yes
| 

| deleted
| `boolean`
| Yes
| 

| juvenile
| `boolean`
| Yes
| 

| usrgroup
| `integer`
| Yes
| 

| claims_returned_count
| `integer`
| Yes
| 

| credit_forward_balance
| `numeric(6,2)`
| Yes
| 

| last_xact_id
| `text`
| Yes
| 

| create_date
| `timestamp with time zone`
| Yes
| 

| expire_date
| `timestamp with time zone`
| Yes
| 

| claims_never_checked_out_count
| `integer`
| Yes
| 

| last_update_time
| `timestamp with time zone`
| Yes
| 

| locale
| `text`
| Yes
| 

|===

== View Definition

[source,sql]
----
 SELECT '-1'::integer AS audit_id,
    now() AS audit_time,
    '-'::text AS audit_action,
    '-1'::integer AS audit_user,
    '-1'::integer AS audit_ws,
    usr.id,
    usr.card,
    usr.profile,
    usr.usrname,
    usr.email,
    usr.passwd,
    usr.standing,
    usr.ident_type,
    usr.ident_value,
    usr.ident_type2,
    usr.ident_value2,
    usr.net_access_level,
    usr.photo_url,
    usr.prefix,
    usr.first_given_name,
    usr.second_given_name,
    usr.family_name,
    usr.suffix,
    usr.guardian,
    usr.pref_prefix,
    usr.pref_first_given_name,
    usr.pref_second_given_name,
    usr.pref_family_name,
    usr.pref_suffix,
    usr.name_keywords,
    usr.name_kw_tsvector,
    usr.alias,
    usr.day_phone,
    usr.evening_phone,
    usr.other_phone,
    usr.mailing_address,
    usr.billing_address,
    usr.home_ou,
    usr.dob,
    usr.active,
    usr.master_account,
    usr.super_user,
    usr.barred,
    usr.deleted,
    usr.juvenile,
    usr.usrgroup,
    usr.claims_returned_count,
    usr.credit_forward_balance,
    usr.last_xact_id,
    usr.create_date,
    usr.expire_date,
    usr.claims_never_checked_out_count,
    usr.last_update_time,
    usr.locale
   FROM actor.usr
UNION ALL
 SELECT actor_usr_history.audit_id,
    actor_usr_history.audit_time,
    actor_usr_history.audit_action,
    actor_usr_history.audit_user,
    actor_usr_history.audit_ws,
    actor_usr_history.id,
    actor_usr_history.card,
    actor_usr_history.profile,
    actor_usr_history.usrname,
    actor_usr_history.email,
    actor_usr_history.passwd,
    actor_usr_history.standing,
    actor_usr_history.ident_type,
    actor_usr_history.ident_value,
    actor_usr_history.ident_type2,
    actor_usr_history.ident_value2,
    actor_usr_history.net_access_level,
    actor_usr_history.photo_url,
    actor_usr_history.prefix,
    actor_usr_history.first_given_name,
    actor_usr_history.second_given_name,
    actor_usr_history.family_name,
    actor_usr_history.suffix,
    actor_usr_history.guardian,
    actor_usr_history.pref_prefix,
    actor_usr_history.pref_first_given_name,
    actor_usr_history.pref_second_given_name,
    actor_usr_history.pref_family_name,
    actor_usr_history.pref_suffix,
    actor_usr_history.name_keywords,
    actor_usr_history.name_kw_tsvector,
    actor_usr_history.alias,
    actor_usr_history.day_phone,
    actor_usr_history.evening_phone,
    actor_usr_history.other_phone,
    actor_usr_history.mailing_address,
    actor_usr_history.billing_address,
    actor_usr_history.home_ou,
    actor_usr_history.dob,
    actor_usr_history.active,
    actor_usr_history.master_account,
    actor_usr_history.super_user,
    actor_usr_history.barred,
    actor_usr_history.deleted,
    actor_usr_history.juvenile,
    actor_usr_history.usrgroup,
    actor_usr_history.claims_returned_count,
    actor_usr_history.credit_forward_balance,
    actor_usr_history.last_xact_id,
    actor_usr_history.create_date,
    actor_usr_history.expire_date,
    actor_usr_history.claims_never_checked_out_count,
    actor_usr_history.last_update_time,
    actor_usr_history.locale
   FROM auditor.actor_usr_history;
----

