= auditor.asset_call_number_lifecycle (view)
:description: View reference for auditor.asset_call_number_lifecycle

xref:schemas/auditor.adoc[↑ auditor schema]

[NOTE]
====
This is a *database view*, not a base table. It has no triggers, indexes, or FK constraints of its own. Querying this view may be more efficient than joining the underlying tables directly.
====

== Columns

[cols="2,2,1,4"]
|===
|Column |Type |Nullable |Notes

| audit_id
| `bigint`
| Yes
| 

| audit_time
| `timestamp with time zone`
| Yes
| 

| audit_action
| `text`
| Yes
| 

| audit_user
| `integer`
| Yes
| 

| audit_ws
| `integer`
| Yes
| 

| id
| `bigint`
| Yes
| 

| creator
| `bigint`
| Yes
| 

| create_date
| `timestamp with time zone`
| Yes
| 

| editor
| `bigint`
| Yes
| 

| edit_date
| `timestamp with time zone`
| Yes
| 

| record
| `bigint`
| Yes
| 

| owning_lib
| `integer`
| Yes
| 

| label
| `text`
| Yes
| 

| deleted
| `boolean`
| Yes
| 

| prefix
| `integer`
| Yes
| 

| suffix
| `integer`
| Yes
| 

| label_class
| `bigint`
| Yes
| 

| label_sortkey
| `text`
| Yes
| 

|===

== View Definition

[source,sql]
----
 SELECT '-1'::integer AS audit_id,
    now() AS audit_time,
    '-'::text AS audit_action,
    '-1'::integer AS audit_user,
    '-1'::integer AS audit_ws,
    call_number.id,
    call_number.creator,
    call_number.create_date,
    call_number.editor,
    call_number.edit_date,
    call_number.record,
    call_number.owning_lib,
    call_number.label,
    call_number.deleted,
    call_number.prefix,
    call_number.suffix,
    call_number.label_class,
    call_number.label_sortkey
   FROM asset.call_number
UNION ALL
 SELECT asset_call_number_history.audit_id,
    asset_call_number_history.audit_time,
    asset_call_number_history.audit_action,
    asset_call_number_history.audit_user,
    asset_call_number_history.audit_ws,
    asset_call_number_history.id,
    asset_call_number_history.creator,
    asset_call_number_history.create_date,
    asset_call_number_history.editor,
    asset_call_number_history.edit_date,
    asset_call_number_history.record,
    asset_call_number_history.owning_lib,
    asset_call_number_history.label,
    asset_call_number_history.deleted,
    asset_call_number_history.prefix,
    asset_call_number_history.suffix,
    asset_call_number_history.label_class,
    asset_call_number_history.label_sortkey
   FROM auditor.asset_call_number_history;
----

